# Generated by Django 4.2.7 on 2024-04-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimsapp', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=122)),
                ('middleName', models.CharField(max_length=122)),
                ('lastName', models.CharField(max_length=122)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('motherName', models.CharField(max_length=122)),
                ('fatherName', models.CharField(max_length=122)),
                ('aadhaarNumber', models.BigIntegerField()),
                ('panNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
