# Generated by Django 4.2.7 on 2024-04-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimsapp', '0004_document_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
