# Generated by Django 5.0.6 on 2024-06-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimsapp', '0006_alter_document_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
